title: Absorbance Analysis
description: A simple GUI to analyze absorbance based plate reader assays
theme: just-the-docs

url: https://www.campbellmusclelab.org

aux_links:
  Absorbance Analysis Repo: https://github.com/Campbell-Muscle-Lab/project_absorbance_analysis
  UKTCVR Repo: https://campbell-muscle-lab.github.io/MATLAB_UKTCVR/
